services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wallet-backend
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: wallet-frontend
    ports:
      - "3000:80"
    restart: unless-stopped
    depends_on:
      - backend
